version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: crud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ranjith@02
      TZ: Asia/Kolkata
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    



  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  user-service:
    build: ./user-service
    depends_on:
      - postgres
      - eureka-server

  product-service:
    build: ./product-service
    depends_on:
      - postgres
      - eureka-server

  order-service:
    build: ./order-service
    depends_on:
      - postgres
      - eureka-server
  auth-service:
    build: ./Auth-Service
    depends_on:
      - eureka-server
      - user-service